### PR TITLE
Upgrade Rust base (9th June) (fb7cca33f) 

### PR DESCRIPTION
**Pull request by dylanmckay**
I've rebased the #137 branch one more time to bring it two months forward - from April to June.

### CODE REVIEW

**Comment by dylanmckay** [comment]
I can successfully compile `blink` to ELF in release mode with this branch.

**Comment by shepmaster** [comment]
> `blink` to ELF in release mode

As far as I'm concerned, that's our current "golden master", so I'd be OK "merging" this as our master branch once we've made sure it compiles on at least a second machine (is the current CI enough for that?)

**Comment by Rahix** [comment]
@shepmaster, I can test compile my HAL crates with it tomorrow if you want

**Comment by dylanmckay** [comment]
@shepmaster the [CI run](https://gitlab.com/avr-rust/rust/-/jobs/227745460) successfully ran `make && make install`.

**Comment by dylanmckay** [comment]
I have force pushed `avr-support` to 9a1785d01750c81d7d5cb533c6f08d0a56749493 and `master` to fb7cca33f8.

**Comment by shepmaster** [comment]
FWIW, I can compile my AVR-GCC-free blink example just fine as well!

**Comment by peacememories** [comment]
hmm, i updated my avr-rust installation, and now my projects fail to build `core` with the following error message:

```
   Compiling compiler_builtins v0.1.16
     Running `rustc --crate-name build_script_build /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.16/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="compiler-builtins"' --cfg 'feature="default"' --cfg 'feature="mem"' -C metadata=622f0871509f1a77 -C extra-filename=-622f0871509f1a77 --out-dir /var/folders/9b/sq7l7grn1_q_bm74x5x67z8r0000gn/T/xargo.PukdOc8v32h1/target/release/build/compiler_builtins-622f0871509f1a77 -L dependency=/var/folders/9b/sq7l7grn1_q_bm74x5x67z8r0000gn/T/xargo.PukdOc8v32h1/target/release/deps --cap-lints allow`
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `compiler_builtins`.
```

Any idea what might have gone wrong?

**Comment by shepmaster** [comment]
> can't find crate for `std`

There certainly isn't a std crate for AVR: no filesystem, no threads, etc. I don't know how your code could have been compiling before.

Unless build scripts use the host system's libstd, in which case it seems like your build might not be complete. Did you try deleting the build artifacts and doing a clean build? Are you following the instructions in the README?

**Comment by peacememories** [comment]
Of course the project itself isn't using `std` (it's for avr after all). It seems the cross compilation of libcore is using it somewhere. When I updated I ultimately cloned the whole repository again and built it. Maybe something's stale in `~/.xargo` `~/.cargo` or `~/.rustup`? I don't know.

**Comment by Rahix** [comment]
I suggest deleting `.xargo` and trying again ... At least I had to do that to get the new version working, but the error message was a different one ...

**Comment by peacememories** [comment]
Deleted .xargo and the whole compiler and built it again, the problem seems to persist.

**Comment by Rahix** [comment]
@peacememories: You are probably using rustup, right?  Which directory did you link the toolchain to, using `rustup toolchain link <...>`?

**Comment by peacememories** [comment]
```
lrwxr-xr-x 69 gabriel 13 Jun 16:14 avr-toolchain -> /Users/user/Library/Rust/avr-rust/build/x86_64-apple-darwin/stage1
```

**Comment by Rahix** [comment]
Try linking against `stage2` instead.  If that doesn't work, set an install prefix in `config.toml`, run `make install` (or `x.py install` iirc) and then link against the directory you installed to

**Comment by peacememories** [comment]
linking against stage2 works. huh. I could've sworn the docs say you should link against stage1?

**Comment by peacememories** [comment]
Thanks anyway, now I can continue working :)

**Comment by shepmaster** [comment]
huh. I would have sworn that I used stage1 (and I likely wrote the README), but I do have it set to stage2 as well:

```
/Users/shep/.rustup/toolchains/avr -> /Users/shep/Projects/avr-rust/build/build/x86_64-apple-darwin/stage2
``` 

I'll change that in the readme.

**Comment by shepmaster** [comment]
>  run `make install`

FWIW, I've never installed Rust using this mechanism in the 4 years I've been using it; I always use my local builds right out of the build directory. I kind of regret that we have it in our README at all.

**Comment by Rahix** [comment]
Darn, I was just about to send you a pull-request with updated instructions :D

**Pull request closed without merging**
