### PR TITLE
Update to rust master (LLVM 8.0)

### PR DESCRIPTION
**Pull request by TimNN**
[Better diff of the changes](https://github.com/TimNN/rust/compare/avr-base...avr).

This PR contains all the patches (somewhat cleaned up) that I've been using to test compiling stock `libcore`. 

With this PR, I can compile stock `libcore` with all `-C opt-level`s except `1` (that is, with `0`, `2`, `3`, `s` and `z`).

### CODE REVIEW

**Comment by TimNN** [comment]
I fixed the issue introduced while rebasing (see https://github.com/avr-rust/rust/issues/92#issuecomment-433713508) and can now indeed compile stock `libcore` for every optimization level except `-O1`. Note that I'm using a target specification for the [`atmega32u4`](https://gist.github.com/TimNN/0fb0195e2ac692e156c03d4d13b9bd4f).

**Comment by shepmaster** [comment]
Note that we are unlikely to actually *merge* this — we tend to just rebase and force-push master since the project as a whole is in such an unstable state. This helps keep the master branch closer to the final PR(s) that we will eventually make.

**Comment by shepmaster** [comment]
I see there's some LLVM submodule updates — have all of those changes been isolated into some state to be submitted into LLVM master? @dylanmckay can push directly to LLVM, as I understand it, so once we have PRs and tests they can start being upstreamed.

**Comment by TimNN** [comment]
> Note that we are unlikely to actually merge this — we tend to just rebase and force-push master

Sure, that's fine.

> I see there's some LLVM submodule updates — have all of those changes been isolated into some state to be submitted into LLVM master?

There are currently five independent patches in separate commits, each to fix one issue reported in this repo. Some are published on [reviews.llvm.org](https://reviews.llvm.org). Which issue / review number is linked from the individual commit messages.

I believe that the three AVR specific patches can be more or less submitted as-is, although they should be reviewed by someone with more LLVM knowledge.

The two general LLVM patches (which are also the ones published on [reviews.llvm.org](https://reviews.llvm.org)) I'm not really sure about. `D53485` can probably submitted as-is, although it may not cover all the cases (see my comments in the review). `D53106` is more complex, and would require some careful review from LLVM people, I believe.

**Comment by TimNN** [comment]
So, today I managed to actually compile _and flash_ a program (that would blink SOS on panic) to an Arduino Leonardo 🎉.

There appear to be some outstanding issues (missing things from `compiler_builtins`<sup>1</sup>, some LLVM issues<sup>2</sup>), but using the following worked around them:

```toml
[profile.release]
panic = "abort" 
codegen-units = 1
lto = true
```

<sup>1</sup>: some symbols are missing (the most serious ones are probably 32 bit shifts), another instance of "ran out of registers" when attempting to implement 128 division, and likely some [incorrect calling conventions](https://github.com/llvm-mirror/llvm/blob/9a78ad0d49cfe6c93c3ff45f5a9910e9943da099/lib/Target/AVR/AVRISelLowering.cpp#L222-L225).
<sup>2</sup>: Compiling with LTO and multiple codegen units triggered an `Assertion failed: (CastInst::castIsValid(opc, C, Ty) && "Invalid constantexpr cast!"), function getCast, file lib/IR/Constants.cpp, line 1512.`

**Comment by dylanmckay** [comment]
Wow, this is great! I mean, really great! Thanks @TimNN 

Thanks for [adding support for the program memory data layout field])https://github.com/avr-rust/rust/pull/115/commits/34e01a223e312eea50a18300c353f635a15c661a), now I don't have to!

Also, I'm going to be pretty inactive the next two weeks or so, exam period. I have no problems delegating commit decisions (like whether this is ready to be force-pushed to `avr-support`) to pair of you, if you both are in agreement. I've just verified, and yes @shepmaster has full write access to all repositories in the organisation. Also, I still will be checking GH from time-to-time but if something's important feel free to hit me up at me@dylanmckay.io and I'll see it straight away.

> I believe that the three AVR specific patches can be more or less submitted as-is, although they should be reviewed by someone with more LLVM knowledge.

I can do that, although it'll be in 2~weeks. I guess, we have to maintain a custom fork anyway so long as `D53485` and `D53106` haven't been committed. Notably, one of those does not currently have a reviewer assigned to it.

**Comment by dylanmckay** [comment]
Raised #116 to track all the LLVM patches to be upstreamed. Assigned to myself.

**Comment by TimNN** [comment]
> That's one particularly curly bug, described at avr-llvm/llvm#163.

Note that by now, it is extremely easy to add the missing symbols to `compiler_builtins`: It requires about 20 lines of glue-code and 0 lines of actual implementation. I'll open a PR there.

**Comment by shepmaster** [comment]
I got enough stuff compiling again that my pure Rust (and a tiny bit of assembly) code with blinking the LED and two-way serial communication is back up and running.

Next will be checking the official AVR blink and then ensuring the two branches have the same interesting commits.

**Comment by shepmaster** [comment]
I've pushed up the forked LLVM and force-pushed this code (more-or-less) to the avr-support branch, thanks so much!

**Pull request closed without merging**
