### PR TITLE
Update version of Rust

### PR DESCRIPTION
**Pull request by dylanmckay**
This PR takes all of the AVR-specific commits from the current `avr-support` branch and applies them directly to the upstream Rust master.

I've removed all of the "Cherry pick fix for <x>" commits, as they complicate the history and cause merge conflicts easily. I've also cleaned up the history a bit so that there are only a handful of avr-rust specific commits.

I've also ensured that all of our commits are prefixed with "[AVR]", and also added "[No Upstream]" to the relevant commits.

When this is good to go, rather than merging this, we should simply force push `avr-support-update` to `avr-support` so that the history is clean.

N.B. The AVR-specific commits are at the top of the branch, but GitHub seems to be showing commits in chronological order rather than showing the commit graph directly.

### CODE REVIEW

**Comment by dylanmckay** [comment]
I now need to update LLVM.

This will be quite straightforward as it looks like the [current](https://github.com/rust-lang/llvm/commits/d9e7d2696e41983b6b5a0b4fac604b4e548a84d3) Rust LLVM version is only a few months old. Looking at the diff between the our current avr-rust/llvm fork, there are only a number of changes that we cherry-picked that aren't in the upstream Rust LLVM fork.

This is because the backend is completely in tree now and so the upgrading process is very easy.

**Comment by dylanmckay** [comment]
I have pushed a new LLVM branch named `avr-rust-experimental`

**Comment by shepmaster** [comment]
I skimmed through the set of patches that are applied on top of Rust master and they look reasonable. I can try compiling it now.

**Comment by shepmaster** [comment]
It does not appear that you have switched to the `avr-rust-experimental` branch — I've got this change locally:

```diff
diff --git a/.gitmodules b/.gitmodules
index 2802c8d639..791c2436cb 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -1,7 +1,7 @@
 [submodule "src/llvm"]
        path = src/llvm
-       url = https://github.com/rust-lang/llvm.git
-       branch = master
+       url = https://github.com/avr-rust/llvm.git
+       branch = avr-rust-experimental
 [submodule "src/rt/hoedown"]
        path = src/rt/hoedown
        url = https://github.com/rust-lang/hoedown.git
diff --git a/src/llvm b/src/llvm
index a6b738c907..ce8e2085be 160000
--- a/src/llvm
+++ b/src/llvm
@@ -1 +1 @@
-Subproject commit a6b738c907ee60e2153f42d8180218bd80b947cc
+Subproject commit ce8e2085bee042b1612dcd99251d46eaeaac831b
```

**Comment by shepmaster** [comment]
I [updated libcore mini](https://github.com/shepmaster/rust-avr-libcore-mini/tree/rust-1.22-rebase) to this version of Rust and was able to compile and flash my board. I think it's good to go, once you switch to the newest LLVM commit in your branch.

**Comment by shepmaster** [comment]
Might be worth updating the layout to `e-p:16:8-i8:8-i16:8-i32:8-i64:8-f32:8-f64:8-n8-a:8` as well.

**Comment by dylanmckay** [comment]
> It does not appear that you have switched to the avr-rust-experimental branch

Fixed

> Might be worth updating the layout to `e-p:16:8-i8:8-i16:8-i32:8-i64:8-f32:8-f64:8-n8-a:8` as well

Fixed

**Comment by dylanmckay** [comment]
I can't seem to get it to work on my machine

When compiling the avr-rust/blink example, I get this

```bash
xargo build --target avr-atmega328p
```

```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --target avr-atmega328p` (exit code: 101)
--- stderr
error: Could not create LLVM TargetMachine for triple: avr-unknown-unknown: No available targets are compatible with this triple.
```

I've tried rebuilding LLVM and Rust from scratch to no avail.

**Comment by shepmaster** [comment]
I use my own target spec, maybe something is different?

```json
{
  "llvm-target": "avr-unknown-unknown",
  "cpu": "atmega328p",

  "target-endian": "little",
  "target-pointer-width": "16",
  "os": "none",
  "target-env": "gnu",
  "target-vendor": "unknown",
  "arch": "avr",
  "data-layout": "e-p:16:8-i8:8-i16:8-i32:8-i64:8-f32:8-f64:8-n8-a:8",
  "executables": true,

  "linker": "avr-gcc",
  "linker-flavor": "gcc",
  "pre-link-args": {
    "gcc": [
      "-mmcu=atmega328p",
      "-nostartfiles",
      "../interrupt_vector.S",
      "../initialize_memory.S"
    ]
  },
  "exe-suffix": ".elf",
  "post-link-args": {
    "gcc": [
      "-Wl,--entry=main",
      "-Wl,--entry=_ivr_irq0",
      "-Wl,--entry=_ivr_irq1",
      "-Wl,--entry=_ivr_pin_change_0",
      "-Wl,--entry=_ivr_pin_change_1",
      "-Wl,--entry=_ivr_pin_change_2",
      "-Wl,--entry=_ivr_watchdog_timer",
      "-Wl,--entry=_ivr_timer2_compare_a",
      "-Wl,--entry=_ivr_timer2_compare_b",
      "-Wl,--entry=_ivr_timer2_overflow",
      "-Wl,--entry=_ivr_timer1_capture",
      "-Wl,--entry=_ivr_timer1_compare_a",
      "-Wl,--entry=_ivr_timer1_compare_b",
      "-Wl,--entry=_ivr_timer1_overflow",
      "-Wl,--entry=_ivr_timer0_compare_a",
      "-Wl,--entry=_ivr_timer0_compare_b",
      "-Wl,--entry=_ivr_timer0_overflow",
      "-Wl,--entry=_ivr_spi_transfer_complete",
      "-Wl,--entry=_ivr_usart_rx_complete",
      "-Wl,--entry=_ivr_usart_udr_empty",
      "-Wl,--entry=_ivr_usart_tx_complete",
      "-Wl,--entry=_ivr_adc_conversion_complete",
      "-Wl,--entry=_ivr_eeprom_ready",
      "-Wl,--entry=_ivr_analog_comparator",
      "-Wl,--entry=_ivr_two_wire_serial_interface",
      "-Wl,--entry=_ivr_store_program_memory_ready"
    ]
  },

  "no-compiler-rt": true
}
```

**Comment by shepmaster** [comment]
Hmm. I pulled down avr-rust/blink. After switching to my fork of libcore-mini, I got a different error:

```
Assertion failed: (InVals.size() == Ins.size() && "LowerFormalArguments didn't emit the correct number of values!"), function LowerArguments, file /Users/shep/Projects/avr-rust/src/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp, line 8141.
```

**Comment by dylanmckay** [comment]
I swapped from building an out-of-tree LLVM (using `--llvm-root=<path>`) to letting Rust build its own LLVM, which fixed the error.

When compiling blink with your new libcore-mini, the compiler itself segfaults

**Comment by shepmaster** [comment]
> the compiler itself segfaults

Maybe you don't have the LLVM assertions enabled, it's likely to be the error message I pasted earlier?

**Comment by dylanmckay** [comment]
I get the same error too

Sounds a lot like #57 eh

**Comment by shepmaster** [comment]
> Sounds a lot like #57 eh

Indeed; I wonder what's so different about my blink and the official blink...

**Comment by shepmaster** [comment]
> about my blink and the official blink...

Oh, it's probably *how* we are building, not *what*:

```
$ xargo build --target avr-atmega328p
   Compiling blink v0.1.0 (file:///Users/shep/Projects/arduino/official/blink)
Assertion failed: (InVals.size() == Ins.size() && "LowerFormalArguments didn't emit the correct number of values!"), function LowerArguments, file /Users/shep/Projects/avr-rust/src/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp, line 8141.
error: Could not compile `blink`.

To learn more, run the command again with --verbose.

$ xargo build --target avr-atmega328p --release

   Compiling arduino v0.1.0
   Compiling blink v0.1.0 (file:///Users/shep/Projects/arduino/official/blink)
    Finished release [optimized] target(s) in 1.8 secs
```

When we are not in release, there's probably a lot more pressure on the registers.

**Comment by shepmaster** [comment]
> how we are building, not what:

Yup, if I build my code in debug mode, then it has the same assertion. My guess is that we haven't actually regressed in any interesting way.

**Comment by dylanmckay** [comment]
Nice spotting, I think if we edit the usage section in the README to include `configure --release`, we should be good to go them

**Comment by dylanmckay** [comment]
Will probably do it in a week or two, have got a lot going on at uni at the moment

If you want to edit the README and land it in the meantime, I've got no problem with that, otherwise it can wait for a bit

**Comment by shepmaster** [comment]
> I think if we edit the usage section in the README to include `configure --release`

To be clear, I mean that when compiling your AVR code, not the compiler, you need to use `--release`

> Will probably do it in a week or two

Would you like me to go ahead and perform all the pushes? I can do that 😸

**Comment by shepmaster** [comment]
Pushed...!

**Pull request closed without merging**
