### PR TITLE
WIP: Rebase to Rust master (LLVM 6.0)

### LINKED ISSUE #90: Rebase ontop of Rust with LLVM 6.0
Rust has recently landed LLVM 6.0 support.

On top of this, it has landed support for multiple LLVM toolchains.

The AVR backend as of LLVM 6.0 has all of the patches included in the avr-rust/llvm fork (but we should double check this). This means that we should have no extra cherry-picked commits for avr-rust, so we will be using the exact same LLVM fork as upstream Rust. We would still very likely need to cherry-pick patches in the future however (but if we can do upstream Rust LLVM upgrades with pace, that is preferable).

With this upgrade, we also have an option:

* Add a separate LLVM toolchain in a similar fashion to the emscripten toolchain. This would allow us to use whatever LLVM fork we want for the AVR target separate from the LLVM submodule used to compile the standard upstream Rust target

### PR DESCRIPTION
**Pull request by dylanmckay**
Also brings in LLVM 6.0 support.

Fixes #90.

### CODE REVIEW

**Comment by shepmaster** [comment]
To be clear, I don't think this will want to be an actual PR, right? We'll just replace our `avr-support` branch?

**Comment by shepmaster** [comment]
Comparing this branch to my local attempt at a rebase (which I never started to compile), everything looks reasonable.

We probably don't want to use `github.com/dylanmckay/llvm.git`, I'm assuming? Is there a reason to immediately re-fork LLVM at this point? I guess we do already have one PR to improve LLVM that isn't in LLVM master / Rust's fork...

**Comment by dylanmckay** [comment]
> To be clear, I don't think this will want to be an actual PR, right? We'll just replace our avr-support branch?

Yes, I've mostly raised this PR to make it accessible.

> We probably don't want to use github.com/dylanmckay/llvm.git, I'm assuming? Is there a reason to immediately re-fork LLVM at this point? I guess we do already have one PR to improve LLVM that isn't in LLVM master / Rust's fork...

I did it on my branch to cherry-pick the fix for #57. As this was only merged yesterday, I suspect we will need to maintain a fork from day 1 in order to do this.

Once this PR is good to go, I will fix up the LLVM submodule to point to the avr-rust org.

**Comment by dylanmckay** [comment]
Also, I've used the compiler to try and build stock `core`.

You can see the code on my [libcore-6.0-experiment](https://github.com/dylanmckay/libcore/tree/libcore-6.0-experiment) branch.

There is a bug that triggers an assertion error because the post-register allocation pseudo instruction pass attempts expand a `COPY` from a `DREGS` to a `GPR8`. This doesn't make much sense because they are different sizes.

**Comment by dylanmckay** [comment]
Also, Rust 6.0 adds a new target specification JSON field

It is `target-c-int-width" 16` from memory. We will need to add this to all of our projects, and likely also rebuild the libcore repository and update all `Xargo.toml` references to it.

**Comment by dylanmckay** [comment]
> There is a bug that triggers an assertion error because the post-register allocation pseudo instruction pass attempts expand a COPY from a DREGS to a GPR8. This doesn't make much sense because they are different sizes.
>
> - myself

I have raised #92 to track this. I suspect it won't affect projects like Arduino, blink, or CHIP-8 because it's choking on a particularly hairy piece of floating point code.

**Comment by shepmaster** [comment]
Closing, we skipped all the way to LLVM 8!

**Pull request closed without merging**
